// Code generated by protoc-gen-go. DO NOT EDIT.
// source: funk/funk.proto

/*
Package funk is a generated protocol buffer package.

It is generated from these files:
	funk/funk.proto

It has these top-level messages:
	Event
	ReturnValue
*/
package funk

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Id        string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Timestamp int64    `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Src       string   `protobuf:"bytes,3,opt,name=src" json:"src,omitempty"`
	Tags      []string `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
	Data      []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *Event) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReturnValue struct {
	Tags []string `protobuf:"bytes,1,rep,name=tags" json:"tags,omitempty"`
	Data []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *ReturnValue) Reset()                    { *m = ReturnValue{} }
func (m *ReturnValue) String() string            { return proto.CompactTextString(m) }
func (*ReturnValue) ProtoMessage()               {}
func (*ReturnValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReturnValue) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ReturnValue) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "funk.Event")
	proto.RegisterType((*ReturnValue)(nil), "funk.ReturnValue")
}

func init() { proto.RegisterFile("funk/funk.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x2b, 0xcd, 0xcb,
	0xd6, 0x07, 0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6, 0x52, 0x3e, 0x17,
	0xab, 0x6b, 0x59, 0x6a, 0x5e, 0x89, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3,
	0x06, 0x67, 0x10, 0x53, 0x66, 0x8a, 0x90, 0x0c, 0x17, 0x67, 0x49, 0x66, 0x6e, 0x6a, 0x71, 0x49,
	0x62, 0x6e, 0x81, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x42, 0x40, 0x48, 0x80, 0x8b, 0xb9,
	0xb8, 0x28, 0x59, 0x82, 0x19, 0xac, 0x1c, 0xc4, 0x14, 0x12, 0xe2, 0x62, 0x29, 0x49, 0x4c, 0x2f,
	0x96, 0x60, 0x51, 0x60, 0xd6, 0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x62, 0x29, 0x89, 0x25, 0x89, 0x12,
	0xac, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x60, 0xb6, 0x92, 0x29, 0x17, 0x77, 0x50, 0x6a, 0x49, 0x69,
	0x51, 0x5e, 0x58, 0x62, 0x4e, 0x69, 0x2a, 0x5c, 0x1b, 0x23, 0x16, 0x6d, 0x4c, 0x08, 0x6d, 0x49,
	0x6c, 0x60, 0x47, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xd7, 0xf6, 0x91, 0xc7, 0x00,
	0x00, 0x00,
}
